/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    customers: CustomerAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    productCategories: ProductCategory;
    orders: Order;
    invoices: Invoice;
    customers: Customer;
    vehicles: Vehicle;
    serviceRecords: ServiceRecord;
    bookings: Booking;
    washServices: WashService;
    vehicleBrands: VehicleBrand;
    vehicleModels: VehicleModel;
    oilSpecifications: OilSpecification;
    oilAdjustmentRules: OilAdjustmentRule;
    oilFinderLeads: OilFinderLead;
    pages: Page;
    legalPages: LegalPage;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    customers: {
      vehicles: 'vehicles';
      orders: 'orders';
      bookings: 'bookings';
    };
    vehicles: {
      serviceHistory: 'serviceRecords';
    };
    vehicleBrands: {
      models: 'vehicleModels';
    };
    vehicleModels: {
      oilSpecifications: 'oilSpecifications';
    };
  };
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    productCategories: ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    serviceRecords: ServiceRecordsSelect<false> | ServiceRecordsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    washServices: WashServicesSelect<false> | WashServicesSelect<true>;
    vehicleBrands: VehicleBrandsSelect<false> | VehicleBrandsSelect<true>;
    vehicleModels: VehicleModelsSelect<false> | VehicleModelsSelect<true>;
    oilSpecifications: OilSpecificationsSelect<false> | OilSpecificationsSelect<true>;
    oilAdjustmentRules: OilAdjustmentRulesSelect<false> | OilAdjustmentRulesSelect<true>;
    oilFinderLeads: OilFinderLeadsSelect<false> | OilFinderLeadsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    legalPages: LegalPagesSelect<false> | LegalPagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ar' | 'en') | ('ar' | 'en')[];
  globals: {
    homepage: Homepage;
    navigation: Navigation;
    siteSettings: SiteSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'ar' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Customer | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CustomerAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username: string;
    email?: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Everything you sell. Prices are in Egyptian pounds. A product is only visible on the website when "Published" is ticked.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Your internal product code. Must be unique.
   */
  sku: string;
  /**
   * Manufacturer, e.g. Mobil, Bosch, Valvoline.
   */
  brand?: string | null;
  category: number | ProductCategory;
  /**
   * Controls where the product can be used, e.g. only "Engine oil" items can be attached to an oil specification.
   */
  productType: 'oil' | 'filter' | 'battery' | 'care' | 'accessory' | 'sparePart';
  /**
   * One or two lines, shown on product cards and search results.
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Leave blank to generate automatically from the name.
   */
  slug?: string | null;
  /**
   * Selling price in EGP.
   */
  price: number;
  /**
   * Old price, shown crossed out. Leave empty if not on sale.
   */
  compareAtPrice?: number | null;
  /**
   * What you paid. Used for profit reports. Never shown publicly.
   */
  costPrice?: number | null;
  /**
   * Reduced automatically when an order is confirmed.
   */
  stockQuantity: number;
  /**
   * Below this, the product shows up in the low-stock report.
   */
  lowStockThreshold?: number | null;
  /**
   * Let customers order this even when stock is zero.
   */
  allowBackorder?: boolean | null;
  unit?: ('piece' | 'litre' | 'pack') | null;
  /**
   * Bottle size in litres. Used to work out how many bottles a car needs.
   */
  volumeLiters?: number | null;
  /**
   * First image is used as the main product photo.
   */
  images?: (number | Media)[] | null;
  /**
   * Any spec you want shown on the product page, e.g. "Viscosity" / "5W-30". Add as many rows as you need.
   */
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Car models this part fits — powers the "fits your car" badge and the filter lookup.
   */
  compatibleVehicles?: (number | VehicleModel)[] | null;
  oilAttributes?: {
    viscosity?: string | null;
    apiSpec?: string | null;
    aceaSpec?: string | null;
    oilType?: ('fullSynthetic' | 'semiSynthetic' | 'mineral') | null;
  };
  filterAttributes?: {
    filterType?: ('oil' | 'air' | 'cabin' | 'fuel') | null;
    /**
     * Manufacturer part number.
     */
    partNumber?: string | null;
  };
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * Untick to hide from the website without deleting.
   */
  isPublished?: boolean | null;
  /**
   * Show in the "Featured products" homepage section.
   */
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The shop menu. Leave "Parent category" empty for a top-level section; pick a parent to nest a sub-category under it. Drag rows to reorder, or set the order number.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCategories".
 */
export interface ProductCategory {
  id: number;
  name: string;
  /**
   * Leave blank to generate automatically from the name.
   */
  slug?: string | null;
  /**
   * Leave empty for a top-level category.
   */
  parent?: (number | null) | ProductCategory;
  description?: string | null;
  /**
   * Used on the homepage category tiles.
   */
  image?: (number | null) | Media;
  /**
   * Small icon shown next to the category name.
   */
  icon?: ('droplet' | 'filter' | 'battery' | 'sparkles' | 'wrench' | 'car' | 'package') | null;
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  /**
   * Show this category in the main menu.
   */
  showInNav?: boolean | null;
  /**
   * Feature it in the homepage categories section.
   */
  showOnHomepage?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every image on the website lives here. Upload once, reuse anywhere.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short description of the image, read aloud by screen readers and shown if the image fails to load.
   */
  alt: string;
  /**
   * Optional photographer/source credit.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * A model belongs to a brand and covers a range of years. List each engine variant sold in those years — the Oil Finder matches on brand + model + year + engine.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicleModels".
 */
export interface VehicleModel {
  id: number;
  name: string;
  brand: number | VehicleBrand;
  /**
   * Leave blank to generate automatically from the name.
   */
  slug?: string | null;
  nameAr?: string | null;
  /**
   * First model year sold.
   */
  yearFrom: number;
  /**
   * Leave blank if still in production.
   */
  yearTo?: number | null;
  bodyType?: ('sedan' | 'hatchback' | 'suv' | 'pickup' | 'van' | 'coupe') | null;
  image?: (number | null) | Media;
  /**
   * Every engine option offered for this model, e.g. "1.6L Petrol 16V". Customers pick one of these in the Oil Finder.
   */
  engines: {
    /**
     * Short key used for matching, e.g. 1.6-petrol.
     */
    code: string;
    /**
     * What the customer sees, e.g. 1.6L Petrol.
     */
    label: string;
    fuelType: 'petrol' | 'diesel' | 'hybrid' | 'cng' | 'electric';
    displacementLiters?: number | null;
    isTurbo?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Uncheck to hide this model from the website.
   */
  isActive?: boolean | null;
  oilSpecifications?: {
    docs?: (number | OilSpecification)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * The car makers customers can pick from. Add a brand here first, then add its models.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicleBrands".
 */
export interface VehicleBrand {
  id: number;
  name: string;
  /**
   * Leave blank to generate automatically from the name.
   */
  slug?: string | null;
  nameAr?: string | null;
  /**
   * Shown in the Oil Finder brand picker.
   */
  logo?: (number | null) | Media;
  /**
   * Country of origin, e.g. Japan.
   */
  country?: string | null;
  /**
   * Uncheck to hide this brand from the website.
   */
  isActive?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  models?: {
    docs?: (number | VehicleModel)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This is what powers the Oil Finder. Add one entry per model + year range + engine. If a car has no entry, the site shows a "we will confirm for you" message and logs an enquiry for you to answer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oilSpecifications".
 */
export interface OilSpecification {
  id: number;
  /**
   * Generated automatically so this entry is easy to recognise in lists.
   */
  title?: string | null;
  vehicleModel: number | VehicleModel;
  /**
   * Must match an engine "code" on the selected model, e.g. 1.6-petrol.
   */
  engineCode: string;
  /**
   * This spec applies from this model year onwards.
   */
  yearFrom: number;
  /**
   * Leave blank to apply to all newer years.
   */
  yearTo?: number | null;
  /**
   * SAE grade, e.g. 5W-30.
   */
  recommendedViscosity: string;
  /**
   * Minimum API service class.
   */
  requiredAPISpec?: string | null;
  requiredACEASpec?: string | null;
  oilType?: ('fullSynthetic' | 'semiSynthetic' | 'mineral') | null;
  /**
   * Total litres for a full oil change, including filling the new filter.
   */
  requiredOilQuantityLiters: number;
  /**
   * The product we recommend first. Shown with an add-to-cart button.
   */
  recommendedOilProduct?: (number | null) | Product;
  /**
   * Shown as "other options that also fit your car".
   */
  alternativeOilProducts?: (number | Product)[] | null;
  /**
   * Manufacturer part number for the oil filter.
   */
  oilFilterPartNumber?: string | null;
  oilFilterProduct?: (number | null) | Product;
  airFilterProduct?: (number | null) | Product;
  cabinFilterProduct?: (number | null) | Product;
  fuelFilterProduct?: (number | null) | Product;
  /**
   * Distance between oil changes, in kilometres.
   */
  recommendedChangeIntervalKm: number;
  /**
   * Maximum time between changes, whichever comes first.
   */
  recommendedChangeIntervalMonths: number;
  /**
   * Shown to the customer under the recommendation. Use for edge cases, e.g. "turbo engine — full synthetic only".
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Move an order through the pipeline with the Status field. Stock is deducted the moment you set it to Confirmed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Generated automatically.
   */
  orderNumber?: string | null;
  /**
   * Empty for guest checkout.
   */
  customer?: (number | null) | Customer;
  /**
   * Phone we call about this order.
   */
  contactPhone: string;
  contactName: string;
  /**
   * Prices are copied in when the order is placed, so later price changes do not alter old orders.
   */
  items: {
    product: number | Product;
    quantity: number;
    /**
     * EGP each.
     */
    priceAtPurchase: number;
    lineTotal?: number | null;
    /**
     * Product name at time of order.
     */
    nameSnapshot?: string | null;
    id?: string | null;
  }[];
  fulfillmentMethod: 'delivery' | 'pickup';
  orderStatus: 'pending' | 'confirmed' | 'preparing' | 'outForDelivery' | 'readyForPickup' | 'completed' | 'cancelled';
  deliveryAddress?: {
    governorate?: string | null;
    city?: string | null;
    street?: string | null;
    building?: string | null;
    apartment?: string | null;
    landmark?: string | null;
  };
  /**
   * Anything the customer asked for.
   */
  customerNote?: string | null;
  /**
   * Internal only.
   */
  staffNotes?: string | null;
  paymentMethod: 'cod' | 'payAtPickup' | 'paymob';
  paymentStatus: 'unpaid' | 'paid' | 'refunded' | 'failed';
  /**
   * Paymob transaction id, filled in automatically for card payments.
   */
  paymentReference?: string | null;
  subtotal?: number | null;
  deliveryFee?: number | null;
  discount?: number | null;
  total?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Search by phone number — it is the fastest way to find a customer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  /**
   * Primary lookup key. Stored as 01XXXXXXXXX.
   */
  phone: string;
  /**
   * Language used for SMS/WhatsApp notifications sent to this customer.
   */
  preferredLanguage?: ('ar' | 'en') | null;
  addresses?:
    | {
        label?: string | null;
        governorate: string;
        city: string;
        street: string;
        building?: string | null;
        apartment?: string | null;
        landmark?: string | null;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  loyaltyPoints?: number | null;
  /**
   * Internal notes. Never shown to the customer.
   */
  notes?: string | null;
  /**
   * Cars registered to this customer.
   */
  vehicles?: {
    docs?: (number | Vehicle)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  orders?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  bookings?: {
    docs?: (number | Booking)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * Every car we service. Search by plate number. The next oil change is worked out automatically from the last service, but you can override it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: number;
  /**
   * Egyptian plate, e.g. "ط ك ع 1234".
   */
  plateNumber: string;
  owner: number | Customer;
  brand: number | VehicleBrand;
  model: number | VehicleModel;
  manufacturingYear: number;
  /**
   * Engine code from the model, e.g. 1.6-petrol.
   */
  engineType?: string | null;
  /**
   * Latest odometer reading, in kilometres.
   */
  currentMileage?: number | null;
  colour?: string | null;
  vin?: string | null;
  oilBrandUsed?: string | null;
  oilViscosity?: string | null;
  oilFilterUsed?: string | null;
  lastServiceDate?: string | null;
  lastServiceMileage?: number | null;
  /**
   * Filled in automatically after a service. You can overwrite it.
   */
  nextOilChangeMileage?: number | null;
  /**
   * Drives the reminder list on the dashboard.
   */
  nextOilChangeDate?: string | null;
  /**
   * Cleared automatically each time the car is serviced.
   */
  reminderSent?: boolean | null;
  /**
   * Used by the vehicle QR sticker. Generated automatically.
   */
  qrCodeSlug?: string | null;
  /**
   * Everything we have ever done to this car.
   */
  serviceHistory?: {
    docs?: (number | ServiceRecord)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Internal only — never shown to the customer.
   */
  staffNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * What was done to a car and when. Saving an oil change here automatically sets the car’s next oil-change date and mileage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "serviceRecords".
 */
export interface ServiceRecord {
  id: number;
  /**
   * Generated automatically.
   */
  summary?: string | null;
  vehicle: number | Vehicle;
  /**
   * Filled in from the car’s owner so customers can see their own history.
   */
  customerSnapshot?: (number | null) | Customer;
  serviceDate: string;
  /**
   * Odometer reading on the day, in km.
   */
  mileageAtService: number;
  serviceTypes: ('oilChange' | 'filterChange' | 'wash' | 'battery' | 'inspection' | 'repair')[];
  workPerformed?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  oilUsed?: (number | null) | Product;
  oilQuantityLiters?: number | null;
  oilViscosityUsed?: string | null;
  filtersUsed?: (number | Product)[] | null;
  partsUsed?:
    | {
        product?: (number | null) | Product;
        /**
         * For parts not in the shop.
         */
        description?: string | null;
        quantity?: number | null;
        unitPrice?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * EGP.
   */
  labourCost?: number | null;
  /**
   * Total charged to the customer, EGP.
   */
  cost: number;
  /**
   * Leave blank and we work it out from the recommended interval for this car. Fill in to override.
   */
  nextServiceOverride?: {
    nextMileage?: number | null;
    nextDate?: string | null;
  };
  /**
   * Technician who did the work.
   */
  performedBy?: (number | null) | User;
  /**
   * Generated invoice, if one was issued.
   */
  invoice?: (number | null) | Invoice;
  updatedAt: string;
  createdAt: string;
}
/**
 * Who can log into this admin panel, and what each person is allowed to do.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Only a Super Admin can change roles.
   */
  role: 'superadmin' | 'manager' | 'technician' | 'salesStaff';
  /**
   * Used for internal contact and WhatsApp notifications.
   */
  phone?: string | null;
  /**
   * Uncheck to suspend this account without deleting it.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Numbered sequentially per year and printable as a PDF. VAT fields are ready for Egyptian tax requirements.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  /**
   * Generated automatically. Never reused.
   */
  invoiceNumber?: string | null;
  customer?: (number | null) | Customer;
  /**
   * Name printed on the invoice.
   */
  customerName: string;
  issueDate: string;
  source: 'order' | 'service' | 'manual';
  status: 'issued' | 'paid' | 'cancelled';
  order?: (number | null) | Order;
  serviceRecord?: (number | null) | ServiceRecord;
  lineItems: {
    description: string;
    quantity: number;
    unitPrice: number;
    lineTotal?: number | null;
    id?: string | null;
  }[];
  subtotal?: number | null;
  /**
   * VAT %. Egypt is 14% by default. Set 0 if not applicable.
   */
  vatRate?: number | null;
  vatAmount?: number | null;
  total?: number | null;
  /**
   * Customer tax registration number, if they need a tax invoice.
   */
  taxRegistrationNumber?: string | null;
  companyName?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Car wash and detailing appointments. Confirm or cancel with the Status field.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  reference?: string | null;
  contactName: string;
  contactPhone: string;
  /**
   * Linked automatically when a logged-in customer books.
   */
  customer?: (number | null) | Customer;
  vehicle?: (number | null) | Vehicle;
  /**
   * Which package the customer booked.
   */
  serviceType: number | WashService;
  requestedDate: string;
  /**
   * Start time, e.g. 14:30.
   */
  requestedTimeSlot: string;
  status: 'pending' | 'confirmed' | 'inProgress' | 'completed' | 'cancelled' | 'noShow';
  customerNote?: string | null;
  /**
   * Internal only.
   */
  staffNotes?: string | null;
  /**
   * Package price when the booking was made.
   */
  priceAtBooking?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Your wash and detailing packages. Add a new package here and it appears on the booking page immediately.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "washServices".
 */
export interface WashService {
  id: number;
  name: string;
  /**
   * Leave blank to generate automatically from the name.
   */
  slug?: string | null;
  description?: string | null;
  /**
   * Price in EGP.
   */
  price: number;
  /**
   * How long a bay is occupied. Used for time slots.
   */
  durationMinutes: number;
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  image?: (number | null) | Media;
  /**
   * Bullet points shown on the package card.
   */
  includes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shows a "Most popular" badge.
   */
  isPopular?: boolean | null;
  /**
   * Untick to stop taking bookings for this package.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Fine-tune the Oil Finder without a developer. Each rule says: "when the car matches these conditions, adjust the recommendation like this." Rules run from lowest priority number to highest and their effects add up.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oilAdjustmentRules".
 */
export interface OilAdjustmentRule {
  id: number;
  /**
   * A short name for you, e.g. "High mileage over 150,000 km".
   */
  name: string;
  engineConditions?: ('excellent' | 'good' | 'consumesOil' | 'rebuilt')[] | null;
  /**
   * Applies when the car has at least this many km.
   */
  minMileageKm?: number | null;
  /**
   * Applies when the car has at most this many km.
   */
  maxMileageKm?: number | null;
  fuelTypes?: ('petrol' | 'diesel' | 'hybrid' | 'cng')[] | null;
  turboOnly?: boolean | null;
  /**
   * Shifts the second number of the SAE grade by 10.
   */
  viscosityShift?: ('none' | 'thicker' | 'thinner') | null;
  /**
   * Multiply the km interval. 0.8 = change 20% sooner. 1 = no change.
   */
  intervalKmMultiplier?: number | null;
  /**
   * Same, for the months interval.
   */
  intervalMonthsMultiplier?: number | null;
  /**
   * Leave empty to keep whatever the spec entry says.
   */
  forceOilType?: ('fullSynthetic' | 'semiSynthetic' | 'mineral') | null;
  /**
   * Extra line shown to the customer with the result, e.g. "Your engine burns oil — check the level every 1,000 km."
   */
  customerNote?: string | null;
  /**
   * Tick for rare cases (e.g. a rebuilt engine) where you want the result marked "our technician will confirm".
   */
  flagForStaffReview?: boolean | null;
  /**
   * Lower numbers run first.
   */
  priority: number;
  /**
   * Uncheck to switch this rule off temporarily.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A customer looked up a car we have no oil specification for. Answer them, then add the missing spec so the site can answer it automatically next time.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oilFinderLeads".
 */
export interface OilFinderLead {
  id: number;
  summary?: string | null;
  brandName?: string | null;
  modelName?: string | null;
  year?: number | null;
  engineLabel?: string | null;
  brand?: (number | null) | VehicleBrand;
  vehicleModel?: (number | null) | VehicleModel;
  mileageKm?: number | null;
  engineCondition?: ('excellent' | 'good' | 'consumesOil' | 'rebuilt') | null;
  contactName?: string | null;
  contactPhone?: string | null;
  status: 'new' | 'contacted' | 'specAdded' | 'closed';
  staffNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Build a page by stacking sections. The address is the slug in the sidebar, e.g. "about" becomes /about.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Leave blank to generate automatically from the name.
   */
  slug?: string | null;
  sections?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            subheading?: string | null;
            /**
             * Wide photo behind the title. Darkened automatically so text stays readable.
             */
            backgroundImage?: (number | null) | Media;
            align?: ('start' | 'center') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageHero';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: (number | null) | Media;
            /**
             * Which side the photo sits on. Mirrors automatically in Arabic.
             */
            imageSide?: ('start' | 'end') | null;
            bullets?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            buttonLabel?: string | null;
            buttonHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  icon?: ('shield' | 'wrench' | 'clock' | 'droplet' | 'truck' | 'sparkles' | 'car' | 'battery') | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'values';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'steps';
          }
        | {
            heading?: string | null;
            /**
             * Three to eight photos work best.
             */
            images: (number | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            /**
             * Phone, WhatsApp, branches and opening hours come from Site Settings.
             */
            heading?: string | null;
            subheading?: string | null;
            /**
             * Show a map for branches that have coordinates.
             */
            showMap?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
        | {
            heading: string;
            body?: string | null;
            backgroundImage?: (number | null) | Media;
            buttons?:
              | {
                  label: string;
                  href: string;
                  style?: ('accent' | 'primary' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBand';
          }
        | {
            /**
             * Small line above the headline.
             */
            eyebrow?: string | null;
            headline: string;
            subheadline?: string | null;
            /**
             * Large landscape photo, at least 1920px wide.
             */
            backgroundImage?: (number | null) | Media;
            buttons?:
              | {
                  label: string;
                  href: string;
                  style?: ('primary' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  icon?:
                    ('droplet' | 'filter' | 'battery' | 'sparkles' | 'wrench' | 'shield' | 'clock' | 'truck') | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            heading?: string | null;
            body?: string | null;
            image?: (number | null) | Media;
            buttonLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'oilFinderCta';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            /**
             * Leave empty to show every category marked "Show on homepage".
             */
            categories?: (number | ProductCategory)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredCategories';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            source?: ('featured' | 'newest' | 'manual') | null;
            products?: (number | Product)[] | null;
            limit?: number | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredProducts';
          }
        | {
            heading: string;
            body?: string | null;
            image?: (number | null) | Media;
            buttonLabel?: string | null;
            buttonHref?: string | null;
            theme?: ('accent' | 'dark' | 'light') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'promoBanner';
          }
        | {
            items?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  quote: string;
                  author: string;
                  carModel?: string | null;
                  rating?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading?: string | null;
            logos?:
              | {
                  image: number | Media;
                  name?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'brandLogos';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            width?: ('narrow' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
      )[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  /**
   * Add a link to the top menu.
   */
  showInHeader?: boolean | null;
  /**
   * Add a link to the footer.
   */
  showInFooter?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Terms of Service, Privacy Policy and Return Policy. Edit the text here — the footer links update automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legalPages".
 */
export interface LegalPage {
  id: number;
  title: string;
  /**
   * Leave blank to generate automatically from the name.
   */
  slug?: string | null;
  /**
   * The full page text. Headings and lists are supported.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Shown to visitors as the "last updated" date.
   */
  lastReviewed?: string | null;
  showInFooter?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'productCategories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'vehicles';
        value: number | Vehicle;
      } | null)
    | ({
        relationTo: 'serviceRecords';
        value: number | ServiceRecord;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'washServices';
        value: number | WashService;
      } | null)
    | ({
        relationTo: 'vehicleBrands';
        value: number | VehicleBrand;
      } | null)
    | ({
        relationTo: 'vehicleModels';
        value: number | VehicleModel;
      } | null)
    | ({
        relationTo: 'oilSpecifications';
        value: number | OilSpecification;
      } | null)
    | ({
        relationTo: 'oilAdjustmentRules';
        value: number | OilAdjustmentRule;
      } | null)
    | ({
        relationTo: 'oilFinderLeads';
        value: number | OilFinderLead;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'legalPages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'customers';
        value: number | Customer;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'customers';
        value: number | Customer;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  sku?: T;
  brand?: T;
  category?: T;
  productType?: T;
  shortDescription?: T;
  description?: T;
  slug?: T;
  price?: T;
  compareAtPrice?: T;
  costPrice?: T;
  stockQuantity?: T;
  lowStockThreshold?: T;
  allowBackorder?: T;
  unit?: T;
  volumeLiters?: T;
  images?: T;
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  compatibleVehicles?: T;
  oilAttributes?:
    | T
    | {
        viscosity?: T;
        apiSpec?: T;
        aceaSpec?: T;
        oilType?: T;
      };
  filterAttributes?:
    | T
    | {
        filterType?: T;
        partNumber?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  isPublished?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCategories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  description?: T;
  image?: T;
  icon?: T;
  displayOrder?: T;
  showInNav?: T;
  showOnHomepage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  contactPhone?: T;
  contactName?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        priceAtPurchase?: T;
        lineTotal?: T;
        nameSnapshot?: T;
        id?: T;
      };
  fulfillmentMethod?: T;
  orderStatus?: T;
  deliveryAddress?:
    | T
    | {
        governorate?: T;
        city?: T;
        street?: T;
        building?: T;
        apartment?: T;
        landmark?: T;
      };
  customerNote?: T;
  staffNotes?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  paymentReference?: T;
  subtotal?: T;
  deliveryFee?: T;
  discount?: T;
  total?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  invoiceNumber?: T;
  customer?: T;
  customerName?: T;
  issueDate?: T;
  source?: T;
  status?: T;
  order?: T;
  serviceRecord?: T;
  lineItems?:
    | T
    | {
        description?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        id?: T;
      };
  subtotal?: T;
  vatRate?: T;
  vatAmount?: T;
  total?: T;
  taxRegistrationNumber?: T;
  companyName?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  preferredLanguage?: T;
  addresses?:
    | T
    | {
        label?: T;
        governorate?: T;
        city?: T;
        street?: T;
        building?: T;
        apartment?: T;
        landmark?: T;
        isDefault?: T;
        id?: T;
      };
  loyaltyPoints?: T;
  notes?: T;
  vehicles?: T;
  orders?: T;
  bookings?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  plateNumber?: T;
  owner?: T;
  brand?: T;
  model?: T;
  manufacturingYear?: T;
  engineType?: T;
  currentMileage?: T;
  colour?: T;
  vin?: T;
  oilBrandUsed?: T;
  oilViscosity?: T;
  oilFilterUsed?: T;
  lastServiceDate?: T;
  lastServiceMileage?: T;
  nextOilChangeMileage?: T;
  nextOilChangeDate?: T;
  reminderSent?: T;
  qrCodeSlug?: T;
  serviceHistory?: T;
  staffNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "serviceRecords_select".
 */
export interface ServiceRecordsSelect<T extends boolean = true> {
  summary?: T;
  vehicle?: T;
  customerSnapshot?: T;
  serviceDate?: T;
  mileageAtService?: T;
  serviceTypes?: T;
  workPerformed?: T;
  oilUsed?: T;
  oilQuantityLiters?: T;
  oilViscosityUsed?: T;
  filtersUsed?: T;
  partsUsed?:
    | T
    | {
        product?: T;
        description?: T;
        quantity?: T;
        unitPrice?: T;
        id?: T;
      };
  labourCost?: T;
  cost?: T;
  nextServiceOverride?:
    | T
    | {
        nextMileage?: T;
        nextDate?: T;
      };
  performedBy?: T;
  invoice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  reference?: T;
  contactName?: T;
  contactPhone?: T;
  customer?: T;
  vehicle?: T;
  serviceType?: T;
  requestedDate?: T;
  requestedTimeSlot?: T;
  status?: T;
  customerNote?: T;
  staffNotes?: T;
  priceAtBooking?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "washServices_select".
 */
export interface WashServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  price?: T;
  durationMinutes?: T;
  displayOrder?: T;
  image?: T;
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  isPopular?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicleBrands_select".
 */
export interface VehicleBrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  nameAr?: T;
  logo?: T;
  country?: T;
  isActive?: T;
  displayOrder?: T;
  models?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicleModels_select".
 */
export interface VehicleModelsSelect<T extends boolean = true> {
  name?: T;
  brand?: T;
  slug?: T;
  nameAr?: T;
  yearFrom?: T;
  yearTo?: T;
  bodyType?: T;
  image?: T;
  engines?:
    | T
    | {
        code?: T;
        label?: T;
        fuelType?: T;
        displacementLiters?: T;
        isTurbo?: T;
        id?: T;
      };
  isActive?: T;
  oilSpecifications?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oilSpecifications_select".
 */
export interface OilSpecificationsSelect<T extends boolean = true> {
  title?: T;
  vehicleModel?: T;
  engineCode?: T;
  yearFrom?: T;
  yearTo?: T;
  recommendedViscosity?: T;
  requiredAPISpec?: T;
  requiredACEASpec?: T;
  oilType?: T;
  requiredOilQuantityLiters?: T;
  recommendedOilProduct?: T;
  alternativeOilProducts?: T;
  oilFilterPartNumber?: T;
  oilFilterProduct?: T;
  airFilterProduct?: T;
  cabinFilterProduct?: T;
  fuelFilterProduct?: T;
  recommendedChangeIntervalKm?: T;
  recommendedChangeIntervalMonths?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oilAdjustmentRules_select".
 */
export interface OilAdjustmentRulesSelect<T extends boolean = true> {
  name?: T;
  engineConditions?: T;
  minMileageKm?: T;
  maxMileageKm?: T;
  fuelTypes?: T;
  turboOnly?: T;
  viscosityShift?: T;
  intervalKmMultiplier?: T;
  intervalMonthsMultiplier?: T;
  forceOilType?: T;
  customerNote?: T;
  flagForStaffReview?: T;
  priority?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oilFinderLeads_select".
 */
export interface OilFinderLeadsSelect<T extends boolean = true> {
  summary?: T;
  brandName?: T;
  modelName?: T;
  year?: T;
  engineLabel?: T;
  brand?: T;
  vehicleModel?: T;
  mileageKm?: T;
  engineCondition?: T;
  contactName?: T;
  contactPhone?: T;
  status?: T;
  staffNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sections?:
    | T
    | {
        pageHero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              align?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              image?: T;
              imageSide?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
        values?:
          | T
          | {
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              heading?: T;
              subheading?: T;
              showMap?: T;
              id?: T;
              blockName?: T;
            };
        ctaBand?:
          | T
          | {
              heading?: T;
              body?: T;
              backgroundImage?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subheadline?: T;
              backgroundImage?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        oilFinderCta?:
          | T
          | {
              heading?: T;
              body?: T;
              image?: T;
              buttonLabel?: T;
              id?: T;
              blockName?: T;
            };
        featuredCategories?:
          | T
          | {
              heading?: T;
              subheading?: T;
              categories?: T;
              id?: T;
              blockName?: T;
            };
        featuredProducts?:
          | T
          | {
              heading?: T;
              subheading?: T;
              source?: T;
              products?: T;
              limit?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        promoBanner?:
          | T
          | {
              heading?: T;
              body?: T;
              image?: T;
              buttonLabel?: T;
              buttonHref?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    carModel?: T;
                    rating?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        brandLogos?:
          | T
          | {
              heading?: T;
              logos?:
                | T
                | {
                    image?: T;
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  showInHeader?: T;
  showInFooter?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legalPages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  lastReviewed?: T;
  showInFooter?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  phone?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Build the homepage by adding sections and dragging them into the order you want. Changes go live as soon as you save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  sections?:
    | (
        | {
            /**
             * Small line above the headline.
             */
            eyebrow?: string | null;
            headline: string;
            subheadline?: string | null;
            /**
             * Large landscape photo, at least 1920px wide.
             */
            backgroundImage?: (number | null) | Media;
            buttons?:
              | {
                  label: string;
                  href: string;
                  style?: ('primary' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  icon?:
                    ('droplet' | 'filter' | 'battery' | 'sparkles' | 'wrench' | 'shield' | 'clock' | 'truck') | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            heading?: string | null;
            body?: string | null;
            image?: (number | null) | Media;
            buttonLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'oilFinderCta';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            /**
             * Leave empty to show every category marked "Show on homepage".
             */
            categories?: (number | ProductCategory)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredCategories';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            source?: ('featured' | 'newest' | 'manual') | null;
            products?: (number | Product)[] | null;
            limit?: number | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredProducts';
          }
        | {
            heading: string;
            body?: string | null;
            image?: (number | null) | Media;
            buttonLabel?: string | null;
            buttonHref?: string | null;
            theme?: ('accent' | 'dark' | 'light') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'promoBanner';
          }
        | {
            items?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  quote: string;
                  author: string;
                  carModel?: string | null;
                  rating?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading?: string | null;
            logos?:
              | {
                  image: number | Media;
                  name?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'brandLogos';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            width?: ('narrow' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The links in the top menu and in the footer. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?:
    | {
        label: string;
        /**
         * Internal path or full URL.
         */
        href: string;
        /**
         * Leave empty for a plain link.
         */
        children?:
          | {
              label: string;
              /**
               * Internal path or full URL.
               */
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              /**
               * Internal path or full URL.
               */
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Small line at the very bottom, e.g. copyright.
   */
  footerNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Logo, contact details, opening hours and social links used across the whole website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  /**
   * Used in the header. SVG or PNG with transparent background.
   */
  logo?: (number | null) | Media;
  /**
   * Optional light version for dark backgrounds.
   */
  logoDark?: (number | null) | Media;
  favicon?: (number | null) | Media;
  /**
   * Main brand colour as a hex code. Used for the menu, links, headings and most buttons.
   */
  primaryColor?: string | null;
  /**
   * Action colour as a hex code. Used sparingly for Add to Cart, Book Now and urgent badges.
   */
  accentColor?: string | null;
  phone?: string | null;
  /**
   * International format, e.g. 201012345678.
   */
  whatsappNumber?: string | null;
  email?: string | null;
  branches?:
    | {
        name: string;
        address: string;
        phone?: string | null;
        /**
         * Google Maps link.
         */
        mapUrl?: string | null;
        latitude?: number | null;
        longitude?: number | null;
        id?: string | null;
      }[]
    | null;
  openingHours?:
    | {
        days: string;
        hours: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'tiktok' | 'youtube' | 'x' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Standard delivery fee in EGP.
   */
  deliveryFee?: number | null;
  /**
   * Order total above which delivery is free. 0 disables it.
   */
  freeDeliveryThreshold?: number | null;
  codEnabled?: boolean | null;
  /**
   * Turn on once your Paymob keys are set in the environment.
   */
  onlinePaymentEnabled?: boolean | null;
  bookingOpenTime?: string | null;
  bookingCloseTime?: string | null;
  /**
   * Length of each bookable slot.
   */
  bookingSlotMinutes?: number | null;
  /**
   * How many cars you can take in one slot (number of bays).
   */
  bookingsPerSlot?: number | null;
  /**
   * Minimum notice before a booking can start.
   */
  bookingLeadTimeHours?: number | null;
  /**
   * Days you do not take bookings at all.
   */
  closedDays?: ('0' | '1' | '2' | '3' | '4' | '5' | '6')[] | null;
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  /**
   * Image shown when the site is shared on social media.
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subheadline?: T;
              backgroundImage?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        oilFinderCta?:
          | T
          | {
              heading?: T;
              body?: T;
              image?: T;
              buttonLabel?: T;
              id?: T;
              blockName?: T;
            };
        featuredCategories?:
          | T
          | {
              heading?: T;
              subheading?: T;
              categories?: T;
              id?: T;
              blockName?: T;
            };
        featuredProducts?:
          | T
          | {
              heading?: T;
              subheading?: T;
              source?: T;
              products?: T;
              limit?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        promoBanner?:
          | T
          | {
              heading?: T;
              body?: T;
              image?: T;
              buttonLabel?: T;
              buttonHref?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    carModel?: T;
                    rating?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        brandLogos?:
          | T
          | {
              heading?: T;
              logos?:
                | T
                | {
                    image?: T;
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  logoDark?: T;
  favicon?: T;
  primaryColor?: T;
  accentColor?: T;
  phone?: T;
  whatsappNumber?: T;
  email?: T;
  branches?:
    | T
    | {
        name?: T;
        address?: T;
        phone?: T;
        mapUrl?: T;
        latitude?: T;
        longitude?: T;
        id?: T;
      };
  openingHours?:
    | T
    | {
        days?: T;
        hours?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  deliveryFee?: T;
  freeDeliveryThreshold?: T;
  codEnabled?: T;
  onlinePaymentEnabled?: T;
  bookingOpenTime?: T;
  bookingCloseTime?: T;
  bookingSlotMinutes?: T;
  bookingsPerSlot?: T;
  bookingLeadTimeHours?: T;
  closedDays?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}